# BUILD file for src/datasystem/common/scheduling
load("//bazel:build_defs.bzl", "ds_cc_library")

package(default_visibility = ["//visibility:public"])

ds_cc_library(
    name = "worker_read_bandwidth_tracker",
    srcs = ["worker_read_bandwidth_tracker.cpp"],
    hdrs = ["worker_read_bandwidth_tracker.h"],
    deps = [
        "//src/datasystem/common/flags:dynamic_flag_config",
        "//src/datasystem/common/log:common_log",
    ],
)
